---
book_repo: docs-book-tanzu-buildpacks
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: 'master'

feedback_enabled: true

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

skip_versioning: true

sections:

- repository:
    name: pivotal/docs-tanzu-buildpacks
  directory: tanzu-buildpacks
  subnav_template: tanzu-buildpacks_subnav_0-n.erb
  product_info:
    use_local_header: true
# update the changelog_href when publishing this book to production
    changelog_href: http://docs-pcf-staging.cfapps.io/tanzu-buildpacks/release-notes.html
    local_header_img: /images/cloud_rings.png
    local_header_title: Tanzu Buildpacks
    search_placeholder: Search Tanzu Buildpacks
    url_prefix: tanzu-buildpacks/
    local_header_links: []
